### ISSUE TITLE
Resque test failing sporadically 

### ISSUE THREAD

**Issue by kbaum** [danmayer/coverband#178]
Noticed this failure:

```
ernel.BigDecimal method instead.
/Users/karlbaum/.gem/ruby/2.5.3/gems/activesupport-4.2.11/lib/active_support/core_ext/enumerable.rb:20: warning: method redefined; discarding old sum
D, [2019-01-27T11:42:47.872306 #20971] DEBUG -- : Coverband: Reported coverage before exit
Run options: --seed 30638

# Running:

...................................................................................................................../Users/karlbaum/.gem/ruby/2.5.3/gems/resque-2.0.0/lib/resque.rb:140: warning: instance variable @data_store not initialized
/Users/karlbaum/.gem/ruby/2.5.3/gems/redis-4.1.0/lib/redis/connection/ruby.rb:210: [BUG] Segmentation fault at 0x0000000110391a3a
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin17]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:
     * ~/Library/Logs/DiagnosticReports
     * /Library/Logs/DiagnosticReports
   for more details.
Don't forget to include the above Crash Report log file in bug reports.

-- Control frame information -----------------------------------------------
c:0039 p:---- s:0207 e:000206 CFUNC  :getaddrinfo
c:0038 p:0034 s:0199 e:000198 METHOD /Users/karlbaum/.gem/ruby/2.5.3/gems/redis-4.1.0/lib/redis/connection/ruby.rb:210
c:0037 p:0161 s:0191 e:000190 METHOD /Users/karlbaum/.gem/ruby/2.5.3/gems/redis-4.1.0/lib/redis/connection/ruby.rb:296
c:0036 p:0070 s:0184 e:000183 METHOD /Users/karlbaum/.gem/ruby/2.5.3/gems/redis-4.1.0/lib/redis/client.rb:342
c:0035 p:0005 s:0179 e:000178 BLOCK  /Users/karlbaum/.gem/ruby/2.5.3/gems/redis-4.1.0/lib/redis/client.rb:104
c:0034 p:0016 s:0176 e:000175 METHOD /Users/karlbaum/.gem/ruby/2.5.3/gems/redis-4.1.0/lib/redis/client.rb:299
c:0033 p:0020 s:0170 e:000169 METHOD /Users/karlbaum/.gem/ruby/2.5.3/gems/redis-4.1.0/lib/redis/client.rb:103
c:0032 p:0009 s:0166 e:000165 METHOD /Users/karlbaum/.gem/ruby/2.5.3/gems/redis-4.1.0/lib/redis/client.rb:249
c:0031 p:0009 s:0162 e:000161 METHOD /Users/karlbaum/.gem/ruby/2.5.3/gems/resque-2.0.0/lib/resque/data_store.rb:81
c:0030 p:0010 s:0158 e:000157 METHOD /Users/karlbaum/.gem/ruby/2.5.3/gems/resque-2.0.0/lib/resque/worker.rb:341
```

Along with this test failure output:

```

[IMPORTANT]
Don't forget to include the Crash Report log file under
DiagnosticReports directory in bug reports.

F.................

Finished in 1.160535s, 122.3574 runs/s, 186.9827 assertions/s.

  1) Failure:
ResqueWorkerTest#test_resque_job_coverage [/Users/karlbaum/workspace/coverband/test/unit/resque_worker_test.rb:22]:
Expected: [1, 1, nil, 1, 1, nil, nil]
  Actual: [1, 1, nil, 1, 0, nil, nil]

142 runs, 217 assertions, 1 failures, 0 errors, 0 skips
[Coveralls] Outside the CI environment, not sending data.
rake aborted!
Command failed with status (1): [ruby -w -I"lib:lib:test" -I"/Users/karlbaum/.gem/ruby/2.5.3/gems/rake-12.3.2/lib" "/Users/karlbaum/.gem/ruby/2.5.3/gems/rake-12.3.2/lib/rake/rake_test_loader.rb" "test/unit/adapters_base_test.rb" "test/unit/adapters_file_store_test.rb" "test/unit/adapters_redis_store_test.rb" "test/unit/background_test.rb" "test/unit/collectors_coverage_test.rb" "test/unit/configuration_test.rb" "test/unit/coverband_test.rb" "test/unit/full_stack_test.rb" "test/unit/middleware_test.rb" "test/unit/rack_server_checkout_test.rb" "test/unit/rails_full_stack_test.rb" "test/unit/reports_base_test.rb" "test/unit/reports_console_test.rb" "test/unit/reports_html_test.rb" "test/unit/reports_web_test.rb" "test/unit/resque_worker_test.rb" "test/unit/utils/file_list_test.rb" "test/unit/utils/lines_classifier_test.rb" "test/unit/utils/result_test.rb" "test/unit/utils/s3_report_test.rb" "test/unit/utils/source_file_line_test.rb" "test/unit/utils/source_file_test.rb" ]
```

**Comment by kbaum** [comment]
Fixed by #181

**Comment by danmayer** [comment]
Does this mean we want to do the alpha release? If so we could do that while I work a bit more on the gem feature... we could maybe get my feature into a beta release or it will slip to 4.0.3 if I hit any issues? I think I can have that company try the alpha if we think the resque stuff is good to go

**Comment by kbaum** [comment]
I think just having resque support is good enough for a release. If we follow semantic versioning, it's enough for a minor release which would be 4.1.0 since it's new functionality but it's backwards compatible. We haven't been following this approach but no harm in starting now 😄.  Let me know what you think.

**Comment by danmayer** [comment]
yeah I have tried to follow semantic versioning but probably screw it up occasionally with small features ;)

Anyways, I say we cut the alpha version and we can have that company give the resque support a test for us. 

Want me to change the version and release alpha or do you want to do that?

As or my feature, I am getting close but it doesn't matter to me if it makes it in 4.1.0 or 4.2.0

**Comment by kbaum** [comment]
Sure! I'll cut the alpha release.

**Comment by kbaum** [comment]
Done. 
https://github.com/danmayer/coverband/commit/0a89a38de36ecadb8c3c9bb7fd97c47112e7fc52
And gem pushed to rubygems.

**Comment by danmayer** [comment]
Great I will ping the email contact and see if they can see if this
resolved the issue.

**Comment by danmayer** [comment]
still seeing this test fail time to time on travis-ci . @kbaum 

```
....assert_equal 1, Coverband.configuration.store.coverage['/home/travis/build/danmayer/coverband/test/unit/test_resque_job.rb']['data'][4]
....................................................................................................................../home/travis/build/danmayer/coverband/test/fake_app/basic_rack.rb:6: warning: method redefined; discarding old call
/home/travis/build/danmayer/coverband/test/fake_app/basic_rack.rb:6: warning: previous definition of call was here
```

https://travis-ci.org/danmayer/coverband/jobs/488820423

Emailed contact they are giving the alpha a shot tonight or tomorrow.

**Comment by kbaum** [comment]
Doh! I thought we had it. Will try and track it down.

**Comment by danmayer** [comment]
dang still hitting this on CI and sometimes locally

```
..............................assert_equal 1, Coverband.configuration.store.coverage['/home/travis/build/danmayer/coverband/test/unit/test_resque_job.rb']['data'][4]
................F
```

**Comment by kbaum** [comment]
Oh.. i wasn't able to make it happen locally previously. Will take a look!

**Comment by danmayer** [comment]
just fixed a different test on master that occurred from the merges, but this one still happens on master for me if I run multiple times in a row... perhaps 50% of my runs

**Comment by kbaum** [comment]
Interesting that you are getting 50% failures rate.. i am using this script to test right now:

```
#!/bin/bash

set -e

for run in {1..1000}
do
  bundle exec rake test
done
```

And all tests are currently succeeding each time. I am using ruby 2.5.3. I wonder if we are doing anything differently?

**Comment by kbaum** [comment]
I am using redis 5.0.2

```
➜  coverband git:(master) ✗ redis-server --version
Redis server v=5.0.2 sha=00000000:0 malloc=libc bits=64 build=6fc0f5745dcba2c3
```
I also just updated all of my gems with a 
```
bundle upate
```

**Comment by kbaum** [comment]
I ran this for a while and it ended up actually failing on a different test eventually but it took a while:

![image](https://user-images.githubusercontent.com/96786/52542442-a9810180-2d6d-11e9-94af-aa260900780e.png)

**Comment by kbaum** [comment]
Modified the script to output the current run number:
```
#!/bin/bash

set -e

for run in {1..1000}
do
  echo "Run number ${run}"
  bundle exec rake test
done
```
Still got the same test failing on the 18th run:
![image](https://user-images.githubusercontent.com/96786/52542790-60cb4780-2d71-11e9-9bfa-273b59db3b62.png)

**Comment by kbaum** [comment]
Another note on that test is that it fails consistently for me if i execute it on it's own:

```
bundle exec m test/unit/rails_gems_full_stack_test.rb
```
![image](https://user-images.githubusercontent.com/96786/52542857-0da5c480-2d72-11e9-809e-3b75081300b5.png)

**Comment by kbaum** [comment]
This appears to address the rails_gem_full_stack_test.rb failures:

https://github.com/danmayer/coverband/pull/192

Was able to consistently reproduce so this one was pretty easy to track down.

**Comment by danmayer** [comment]
interesting so this seems to be timing conflicts... Might need a cleaner way to fully isolate some of our Coverband tests since they normally with different configurations assume to be run in full process isolation.

**Comment by danmayer** [comment]
Anyways merge that and if we stop having any travis failures cool... funny I didn't see that one fail for me often but it did about 1 out of 10 times have that test fail vs the resque test.

**Comment by kbaum** [comment]
Did some more experimentation on this on the morning commute. Noticing that `test/unit/rails_full_stack_test.rb` was failing every 10th time. By including as a reload_file, was able to execute 50+ times in a row with no failure.  My theory is that in some cases, the dummy_controller was being required before the `Coverage.start` which causes class load coverage to be missed.

That being said, it looks like we are still getting some failures after this change so i will look into this again later.

https://travis-ci.org/danmayer/coverband/builds/491654448?utm_medium=notification&utm_source=email

**Comment by danmayer** [comment]
given how coverband works and some of the issues with load order and background processes etc... this could be an interesting approach at test isolation. Our actual tests (not benchmarks) are pretty fast

https://www.gregnavis.com/articles/how-to-reduce-test-interference-in-minitest.html

**Comment by kbaum** [comment]
Has this happened of late?

**Comment by danmayer** [comment]
no let's close this out
